### ISSUE TITLE
token校验完之后输入门诊下拉框一直是空的

### ISSUE THREAD

**Issue by jesselxl** [iamobj/auto-vacc#3]
![image](https://user-images.githubusercontent.com/31544820/120738733-e5ce6200-c522-11eb-986c-d783cde38ba2.png)
如图，没有门诊选项，大佬需要设置什么吗

**Comment by iamobj** [comment]
今天早上发现分接口参数做了加密，比如获取接种门诊接口，正在研究寻找加密函数，找到了的话 我会马上更新一版出来

**Comment by keeleys** [comment]
今天参数加密了。

**Comment by iamobj** [comment]
0.2.0 已经发布，在 [releases](https://github.com/iamobj/auto-vacc/releases) 可下载0.20版本
