### ISSUE TITLE
老哥报 Uncaught TypeError: fs.existsSync is not a function 是啥原因

### ISSUE THREAD

**Issue by zhoujingfu** [iamobj/auto-vacc#5]
老哥报 Uncaught TypeError: fs.existsSync is not a function 是啥原因

**Comment by iamobj** [comment]
什么情况下出现的，是首次打开软件就报的吗

**Comment by iamobj** [comment]
我这边无法复现，不知道你是什么情况下遇到的，这边就先关了这个 issue，有问题再打开
