### ISSUE TITLE
电脑版微信的 token 无法通过 /crmobile/registerUser/getUserInfo 接口的校验

### ISSUE THREAD

**Issue by BooksLiu** [iamobj/auto-vacc#7]
拿到的是 /miWeixin/wx/getRegisterUserInfo?personageType=1 接口的 token 如下图:
![image](https://user-images.githubusercontent.com/13762603/121119536-5db3c980-c84e-11eb-9da7-2856a489e389.png)

**Comment by iamobj** [comment]
miWeixin 路径开头的，不行的，需要看 crmobile 路径开头的接口

**Comment by BooksLiu** [comment]
/crmobile/registerUser/getUserInfo 这个接口我没抓到过

其实看 crmobile 开头的接口的 token 就可以了
